# Generated by Django 4.2.2 on 2023-07-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image5',
        ),
    ]
